### ISSUE TITLE
Need content pages?

### ISSUE THREAD

**Issue by roualdes** [roualdes/website#5]
@KathyGray do you want me to post content pages that list the labs associated with each class?  This is done with the files `views/math105.pug` and `views/math450.pug`.  

Or are you going to do your own content management, on say Blackboard?

**Comment by KathyGray** [comment]
For now I would say no. They are currently going to be set up in BBLearn. We will see how it goes.

**Comment by roualdes** [comment]
Great.  Thanks.  I'll take them down.
